spring:
  application:
    name: microservice-second

server:
  port: 0
  servlet:
    context-path: /microservice-2

eureka:
  client:
    service-url:
      defaultZone: ${REGISTER_URI:http://localhost:8761/eureka}
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include:
          - httptrace
          - info
          - health
  endpoint:
    httptrace:
      enabled: true