spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: micro1
          uri: lb://MICROSERVICE-FIRST
          filters:
            - RewritePath=/micro1, /microservice-1
          predicates:
            - Path=/micro1/**
        - id: micro2
          uri: lb://microservice-second
          predicates:
            - Path=/micro2/**
          filters:
            - RewritePath=/micro2, /microservice-2


server:
  port: 9090
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${REGISTER_URI:http://register/eureka}

management:
  endpoints:
    web:
      exposure:
        include:
          - gateway
          - info
          - health
  endpoint:
    gateway:
      enabled: true